=== Megha2522/Full_Stack_Development-Training-V-sem/web tech exp 4/students.dtd
<!ELEMENT Students (Student+)>
<!ELEMENT Student (RollNo, Marks, TotalMarks, Percentage)>
<!ELEMENT RollNo (#PCDATA)>
<!ELEMENT Marks (#PCDATA)>
<!ELEMENT TotalMarks (#PCDATA)>
<!ELEMENT Percentage (#PCDATA)>

=== Megha2522/Full_Stack_Development-Training-V-sem/web tech exp 4/text.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="students.xsl"?>
<!DOCTYPE Students SYSTEM "students.dtd">
<Students>
    <Student>
        <RollNo>101</RollNo>
        <Marks>450</Marks>
        <TotalMarks>500</TotalMarks>
        <Percentage>90</Percentage>
    </Student>
    <Student>
        <RollNo>102</RollNo>
        <Marks>400</Marks>
        <TotalMarks>500</TotalMarks>
        <Percentage>80</Percentage>
    </Student>
    <Student>
        <RollNo>103</RollNo>
        <Marks>350</Marks>
        <TotalMarks>500</TotalMarks>
        <Percentage>70</Percentage>
    </Student>
    <Student>
        <RollNo>104</RollNo>
        <Marks>300</Marks>
        <TotalMarks>500</TotalMarks>
        <Percentage>60</Percentage>
    </Student>
    <Student>
        <RollNo>105</RollNo>
        <Marks>475</Marks>
        <TotalMarks>500</TotalMarks>
        <Percentage>95</Percentage>
    </Student>
    <Student>
        <RollNo>106</RollNo>
        <Marks>425</Marks>
        <TotalMarks>500</TotalMarks>
        <Percentage>85</Percentage>
    </Student>
    <Student>
        <RollNo>107</RollNo>
        <Marks>380</Marks>
        <TotalMarks>500</TotalMarks>
        <Percentage>76</Percentage>
    </Student>
    <Student>
        <RollNo>108</RollNo>
        <Marks>320</Marks>
        <TotalMarks>500</TotalMarks>
        <Percentage>64</Percentage>
    </Student>
    <Student>
        <RollNo>109</RollNo>
        <Marks>290</Marks>
        <TotalMarks>500</TotalMarks>
        <Percentage>58</Percentage>
    </Student>
    <Student>
        <RollNo>110</RollNo>
        <Marks>470</Marks>
        <TotalMarks>500</TotalMarks>
        <Percentage>94</Percentage>
    </Student>
</Students>
